/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl01_michell_alvarez_pregunta01;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Michell
 */
public class Carrera extends javax.swing.JDialog {

    /**
     * Creates new form Carrera
     */
    public Carrera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    int contador1 = 0;
    int contador2 = 0;
    int contador3 = 0;
    int contador4 = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeProgreso1 = new javax.swing.JProgressBar();
        porcentajeCaballo1 = new javax.swing.JLabel();
        barraDeProgreso2 = new javax.swing.JProgressBar();
        porcentajeCaballo2 = new javax.swing.JLabel();
        barraDeProgreso3 = new javax.swing.JProgressBar();
        porcentajeCaballo3 = new javax.swing.JLabel();
        barraDeProgreso4 = new javax.swing.JProgressBar();
        porcentajeCaballo4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        caballoGanador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        porcentajeCaballo1.setText("0%");

        porcentajeCaballo2.setText("0%");

        porcentajeCaballo3.setText("0%");

        porcentajeCaballo4.setText("0%");

        jLabel1.setText("El ganador es: ");

        jLabel2.setText("Caballo 1");

        jLabel3.setText("Caballo 2");

        jLabel4.setText("Caballo 3");

        jLabel5.setText("Caballo 4");

        btnInicio.setText("Iniciar");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barraDeProgreso4, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                            .addComponent(barraDeProgreso3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barraDeProgreso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barraDeProgreso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(porcentajeCaballo1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentajeCaballo2)
                            .addComponent(porcentajeCaballo3)
                            .addComponent(porcentajeCaballo4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(caballoGanador))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(btnInicio)))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(porcentajeCaballo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(barraDeProgreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraDeProgreso2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentajeCaballo2)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraDeProgreso3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentajeCaballo3)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraDeProgreso4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentajeCaballo4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(caballoGanador))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInicio)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        empezarHilo1();
        empezarHilo2();
        empezarHilo3();
        empezarHilo4();
        empezarHilo5();
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Carrera dialog = new Carrera(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraDeProgreso1;
    private javax.swing.JProgressBar barraDeProgreso2;
    private javax.swing.JProgressBar barraDeProgreso3;
    private javax.swing.JProgressBar barraDeProgreso4;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel caballoGanador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel porcentajeCaballo1;
    private javax.swing.JLabel porcentajeCaballo2;
    private javax.swing.JLabel porcentajeCaballo3;
    private javax.swing.JLabel porcentajeCaballo4;
    // End of variables declaration//GEN-END:variables

    private void empezarHilo1() {
        Thread hilo1 = new Thread(new Runnable() {

            int x = 0;

            @Override
            public void run() {

                try {

                    while (x <= 100) {

                        int min = 1;
                        int max = 15;

                        int valor = (int) (Math.random() * (max - min)) + min;
                        x = x + valor;
                        barraDeProgreso1.setValue(x);
                        porcentajeCaballo1.setText(x + "%");
                        if (x > 100) {
                            barraDeProgreso1.setValue(100);
                            porcentajeCaballo1.setText(100 + "%");
                        }

                        x++;
                        contador1 = contador1 + 1;
                        Thread.sleep(100);
                    }

                } catch (Exception e) {
                    System.out.println("Excepción: " + e.getMessage());

                }

            }

        });
        hilo1.start();
    }

    private void empezarHilo2() {
        Thread hilo2 = new Thread(new Runnable() {

            int x = 0;

            @Override
            public void run() {

                try {

                    while (x <= 100) {

                        int min = 1;
                        int max = 15;

                        int valor = (int) (Math.random() * (max - min)) + min;
                        x = x + valor;
                        barraDeProgreso2.setValue(x);
                        porcentajeCaballo2.setText(x + "%");
                        if (x > 100) {
                            barraDeProgreso2.setValue(100);
                            porcentajeCaballo2.setText(100 + "%");
                        }

                        x++;
                        contador2 = contador2 + 1;
                        Thread.sleep(100);
                    }

                } catch (Exception e) {
                    System.out.println("Excepción: " + e.getMessage());

                }

            }
        });
        hilo2.start();
    }

    private void empezarHilo3() {
        Thread hilo3 = new Thread(new Runnable() {

            int x = 0;

            @Override
            public void run() {

                try {

                    while (x <= 100) {

                        int min = 1;
                        int max = 15;

                        int valor = (int) (Math.random() * (max - min)) + min;
                        x = x + valor;
                        barraDeProgreso3.setValue(x);
                        porcentajeCaballo3.setText(x + "%");
                        if (x > 100) {
                            barraDeProgreso3.setValue(100);
                            porcentajeCaballo3.setText(100 + "%");
                        }

                        x++;
                        contador3 = contador3 + 1;
                        Thread.sleep(100);
                    }

                } catch (Exception e) {
                    System.out.println("Excepción: " + e.getMessage());

                }

            }
        });
        hilo3.start();
    }

    private void empezarHilo4() {
        Thread hilo4 = new Thread(new Runnable() {

            int x = 0;

            @Override
            public void run() {

                try {

                    while (x <= 100) {

                        int min = 1;
                        int max = 15;

                        int valor = (int) (Math.random() * (max - min)) + min;

                        x = x + valor;
                        barraDeProgreso4.setValue(x);
                        porcentajeCaballo4.setText(x + "%");
                        if (x > 100) {
                            barraDeProgreso4.setValue(100);
                            porcentajeCaballo4.setText(100 + "%");
                        }

                        x++;
                        contador4 = contador4 + 1;
                        Thread.sleep(100);
                    }

                } catch (Exception e) {
                    System.out.println("Excepción: " + e.getMessage());

                }

            }
        });
        hilo4.start();
    }

    private void empezarHilo5() {
        Thread hilo5 = new Thread(new Runnable() {

            @Override
            public void run() {

                try {
                    Thread.sleep(4000);
                    int[] arrayCaballos = {contador1, contador2, contador3, contador4};
                    int menor = arrayCaballos[0];
                    int posicion=0;
                    for (int i = 0; i < 4; i++) {
                        if (arrayCaballos[i] < menor) {
                            menor = arrayCaballos[i];
                            posicion=i;
                        }
                    
                    }

                    caballoGanador.setText("Caballo "+Integer.toString(posicion+1));

                    contador1 = 0;
                    contador2 = 0;
                    contador3 = 0;
                    contador4 = 0;

                } catch (InterruptedException ex) {
                    Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        hilo5.start();
    }

}
